### PR TITLE
Add dev RDS

### PR DESCRIPTION
**Pull request by laramackey**
**MR only for develop**

Terraform to manage the ampify-catalogue database in AWS.
For information on resources please look at the [readme](https://github.com/Focusrite-Novation/aws-warehouse-infra/blob/add-dev-rds/README.md)

### CODE REVIEW

**Comment by tehpsy** [comment]
Would love to review this but I don't feel qualified! Is it worth doing a walkthrough?

**Comment by smbkr** [comment]
Yeah I think I'd benefit from a walkthrough of this PR too!

**Comment by laramackey** [comment]
cool I'm free all day if we wanna do a call? I'll let you suggest a time @tehpsy as I don't know your working hours

**Comment by tehpsy** [comment]
@laramackey @smbkr 11:15?

**Comment by laramackey** [comment]
Good with me @tehpsy

**Pull request merged**
